version: 2.1
orbs:
  ruby: circleci/ruby@1.1
  node: circleci/node@4.3

jobs:
  install_ruby_dependencies:
    docker:
      - image: cimg/ruby:3.0.0
    environment:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
    steps:
      - checkout
      - run: sudo sh -c 'apt update; apt install -y libsqlite3-dev'
      - ruby/install-deps
  install_javascript_dependencies:
    docker:
      - image: cimg/ruby:3.0.0-node
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
  run_tests:
    docker:
      - image: cimg/ruby:3.0.0-browsers
      - image: circleci/postgres:11.0-alpine
      - image: circleci/redis
    parallelism: 2
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgresql://postgres@localhost/spree_test
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432
      - run:
          name: Setup DB
          command: bundle exec rails db:create db:schema:load
      - run:
          name: Precompile assets
          command: bundle exec rails assets:precompile
      - ruby/rspec-test
      - store_artifacts:
          path: tmp/capybara

workflows:
  version: 2
  main:
    jobs:
      - install_ruby_dependencies
      - install_javascript_dependencies
      - run_tests:
          requires:
            - install_ruby_dependencies
            - install_javascript_dependencies
