default:
  navigation:
    - title: Dřevo
      subtitle:
      url: /t/drevo
      items:
        - :title: Dekorace do pokoje
          :url: /t/kategorie/drevo/dekorace-do-pokoje
      promo_banners:
        - subtitle:
          title: Hrazdička
          url: /products/hrazdicka
          image: 'meganav/promo_banner_left-first-category.jpg'
    - title: Látka
      subtitle:
      url: /t/latka
      items:
        - :title: Chrastítka
          :url: /t/kategorie/latka/chrastitka
        - :title: Doplňky na hrazdičku
          :url: /t/kategorie/latka/doplnky-na-hrazdicku
        - :title: Dekorace do pokoje
          :url: /t/kategorie/latka/dekorace-do-pokoje
      promo_banners:
        - subtitle:
          title: Dekorace
          url: /t/kategorie/latka/dekorace-do-pokoje
          image: 'meganav/promo_banner_left-second-category.jpg'
    - title: Papír
      subtitle:
      url: /t/papir
      items:
        - :title: Pohádkové kartičky
          :url: /t/kategorie/papir/pohadkove-karticky
      promo_banners:
        - subtitle: Pro rodiče
          title: Pohádkové karty
          url: /t/kategorie/papir/pohadkove-karticky
          image: 'meganav/promo_banner_left-third-category.jpg'

fr:
  navigation:
    - title: Femmes
      url: /fr/t/women
      promo_banners:
        - subtitle: Nouvelle collection
          title: Été 2021
          url: /fr/t/new-collection/summer-2021
          image: 'meganav/promo_banner_left-first-category.jpg'
        - subtitle: Offres spéciales
          url: /fr/t/special-offers/30-percent-off
          image: 'meganav/promo_banner_right-first-category.jpg'
    - title: Hommes
      url: /fr/t/men
      promo_banners:
        - subtitle: Nouvelle collection
          title: Été 2021
          url: /fr/t/new-collection/summer-2021
          image: 'meganav/promo_banner_left-second-category.jpg'
        - subtitle: Offres spéciales
          url: /fr/t/special-offers/30-percent-off
          image: 'meganav/promo_banner_right-second-category.jpg'
    - title: Vêtements de sport
      url: /fr/t/sportswear
      promo_banners:
        - subtitle: Nouvelle collection
          title: Été 2021
          url: /fr/t/new-collection/summer-2021
          image: 'meganav/promo_banner_left-third-category.jpg'
        - subtitle: Offres spéciales
          url: /fr/t/special-offers/30-percent-off
          image: 'meganav/promo_banner_right-third-category.jpg'
